<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class m011_authority_pattern_seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 1],
            ['proxy_input_menu' => 0,
            'proxy_attendance_input' => 0,
            'proxy_input_target_setting' => 0,
            'attendance_admin_menu' => 0,
            'attendance_admin_inquiry_approval' => 0,
            'attendance_admin_work_vacation_management' => 0,
            'attendance_admin_daily_report' => 0,
            'attendance_admin_approval_target_setting' => 0,
            'office_menu' => 0,
            'office_attendance_input' => 0,
            'office_work_vacation_management' => 0,
            'office_closing' => 0,
            'office_vacation_management' => 0,
            'office_general_search' => 0,
            'office_master_management' => 0,
            'general_affairs_menu' => 0,
            'general_affairs_attendance_input' => 0,
            'general_affairs_work_vacation_management' => 0,
            'general_affairs_closing' => 0,
            'general_affairs_general_search' => 0,
            'general_affairs_vacation_management' => 0,
            'general_affairs_data_input_output' => 0,
            'general_affairs_master_management' => 0,
            'detail_no' => 1,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 2],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 0,
            'attendance_admin_menu' => 0,
            'attendance_admin_inquiry_approval' => 0,
            'attendance_admin_work_vacation_management' => 0,
            'attendance_admin_daily_report' => 0,
            'attendance_admin_approval_target_setting' => 0,
            'office_menu' => 0,
            'office_attendance_input' => 0,
            'office_work_vacation_management' => 0,
            'office_closing' => 0,
            'office_vacation_management' => 0,
            'office_general_search' => 0,
            'office_master_management' => 0,
            'general_affairs_menu' => 0,
            'general_affairs_attendance_input' => 0,
            'general_affairs_work_vacation_management' => 0,
            'general_affairs_closing' => 0,
            'general_affairs_general_search' => 0,
            'general_affairs_vacation_management' => 0,
            'general_affairs_data_input_output' => 0,
            'general_affairs_master_management' => 0,
            'detail_no' => 2,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 3],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 1,
            'attendance_admin_menu' => 0,
            'attendance_admin_inquiry_approval' => 0,
            'attendance_admin_work_vacation_management' => 0,
            'attendance_admin_daily_report' => 0,
            'attendance_admin_approval_target_setting' => 0,
            'office_menu' => 0,
            'office_attendance_input' => 0,
            'office_work_vacation_management' => 0,
            'office_closing' => 0,
            'office_vacation_management' => 0,
            'office_general_search' => 0,
            'office_master_management' => 0,
            'general_affairs_menu' => 0,
            'general_affairs_attendance_input' => 0,
            'general_affairs_work_vacation_management' => 0,
            'general_affairs_closing' => 0,
            'general_affairs_general_search' => 0,
            'general_affairs_vacation_management' => 0,
            'general_affairs_data_input_output' => 0,
            'general_affairs_master_management' => 0,
            'detail_no' => 3,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 4],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 0,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 0,
            'office_menu' => 0,
            'office_attendance_input' => 0,
            'office_work_vacation_management' => 0,
            'office_closing' => 0,
            'office_vacation_management' => 0,
            'office_general_search' => 0,
            'office_master_management' => 0,
            'general_affairs_menu' => 0,
            'general_affairs_attendance_input' => 0,
            'general_affairs_work_vacation_management' => 0,
            'general_affairs_closing' => 0,
            'general_affairs_general_search' => 0,
            'general_affairs_vacation_management' => 0,
            'general_affairs_data_input_output' => 0,
            'general_affairs_master_management' => 0,
            'detail_no' => 4,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 5],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 1,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 0,
            'office_menu' => 0,
            'office_attendance_input' => 0,
            'office_work_vacation_management' => 0,
            'office_closing' => 0,
            'office_vacation_management' => 0,
            'office_general_search' => 0,
            'office_master_management' => 0,
            'general_affairs_menu' => 0,
            'general_affairs_attendance_input' => 0,
            'general_affairs_work_vacation_management' => 0,
            'general_affairs_closing' => 0,
            'general_affairs_general_search' => 0,
            'general_affairs_vacation_management' => 0,
            'general_affairs_data_input_output' => 0,
            'general_affairs_master_management' => 0,
            'detail_no' => 5,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 6],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 0,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 1,
            'office_menu' => 0,
            'office_attendance_input' => 0,
            'office_work_vacation_management' => 0,
            'office_closing' => 0,
            'office_vacation_management' => 0,
            'office_general_search' => 0,
            'office_master_management' => 0,
            'general_affairs_menu' => 0,
            'general_affairs_attendance_input' => 0,
            'general_affairs_work_vacation_management' => 0,
            'general_affairs_closing' => 0,
            'general_affairs_general_search' => 0,
            'general_affairs_vacation_management' => 0,
            'general_affairs_data_input_output' => 0,
            'general_affairs_master_management' => 0,
            'detail_no' => 6,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 7],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 1,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 1,
            'office_menu' => 0,
            'office_attendance_input' => 0,
            'office_work_vacation_management' => 0,
            'office_closing' => 0,
            'office_vacation_management' => 0,
            'office_general_search' => 0,
            'office_master_management' => 0,
            'general_affairs_menu' => 0,
            'general_affairs_attendance_input' => 0,
            'general_affairs_work_vacation_management' => 0,
            'general_affairs_closing' => 0,
            'general_affairs_general_search' => 0,
            'general_affairs_vacation_management' => 0,
            'general_affairs_data_input_output' => 0,
            'general_affairs_master_management' => 0,
            'detail_no' => 7,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 8],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 0,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 0,
            'office_menu' => 1,
            'office_attendance_input' => 1,
            'office_work_vacation_management' => 1,
            'office_closing' => 1,
            'office_vacation_management' => 1,
            'office_general_search' => 1,
            'office_master_management' => 1,
            'general_affairs_menu' => 0,
            'general_affairs_attendance_input' => 0,
            'general_affairs_work_vacation_management' => 0,
            'general_affairs_closing' => 0,
            'general_affairs_general_search' => 0,
            'general_affairs_vacation_management' => 0,
            'general_affairs_data_input_output' => 0,
            'general_affairs_master_management' => 0,
            'detail_no' => 8,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 9],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 1,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 0,
            'office_menu' => 1,
            'office_attendance_input' => 1,
            'office_work_vacation_management' => 1,
            'office_closing' => 1,
            'office_vacation_management' => 1,
            'office_general_search' => 1,
            'office_master_management' => 1,
            'general_affairs_menu' => 0,
            'general_affairs_attendance_input' => 0,
            'general_affairs_work_vacation_management' => 0,
            'general_affairs_closing' => 0,
            'general_affairs_general_search' => 0,
            'general_affairs_vacation_management' => 0,
            'general_affairs_data_input_output' => 0,
            'general_affairs_master_management' => 0,
            'detail_no' => 9,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 10],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 0,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 1,
            'office_menu' => 1,
            'office_attendance_input' => 1,
            'office_work_vacation_management' => 1,
            'office_closing' => 1,
            'office_vacation_management' => 1,
            'office_general_search' => 1,
            'office_master_management' => 1,
            'general_affairs_menu' => 0,
            'general_affairs_attendance_input' => 0,
            'general_affairs_work_vacation_management' => 0,
            'general_affairs_closing' => 0,
            'general_affairs_general_search' => 0,
            'general_affairs_vacation_management' => 0,
            'general_affairs_data_input_output' => 0,
            'general_affairs_master_management' => 0,
            'detail_no' => 10,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 11],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 1,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 1,
            'office_menu' => 1,
            'office_attendance_input' => 1,
            'office_work_vacation_management' => 1,
            'office_closing' => 1,
            'office_vacation_management' => 1,
            'office_general_search' => 1,
            'office_master_management' => 1,
            'general_affairs_menu' => 0,
            'general_affairs_attendance_input' => 0,
            'general_affairs_work_vacation_management' => 0,
            'general_affairs_closing' => 0,
            'general_affairs_general_search' => 0,
            'general_affairs_vacation_management' => 0,
            'general_affairs_data_input_output' => 0,
            'general_affairs_master_management' => 0,
            'detail_no' => 11,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 12],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 0,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 0,
            'office_menu' => 1,
            'office_attendance_input' => 1,
            'office_work_vacation_management' => 1,
            'office_closing' => 1,
            'office_vacation_management' => 1,
            'office_general_search' => 1,
            'office_master_management' => 1,
            'general_affairs_menu' => 1,
            'general_affairs_attendance_input' => 1,
            'general_affairs_work_vacation_management' => 1,
            'general_affairs_closing' => 1,
            'general_affairs_general_search' => 1,
            'general_affairs_vacation_management' => 1,
            'general_affairs_data_input_output' => 1,
            'general_affairs_master_management' => 1,
            'detail_no' => 12,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 13],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 1,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 0,
            'office_menu' => 1,
            'office_attendance_input' => 1,
            'office_work_vacation_management' => 1,
            'office_closing' => 1,
            'office_vacation_management' => 1,
            'office_general_search' => 1,
            'office_master_management' => 1,
            'general_affairs_menu' => 1,
            'general_affairs_attendance_input' => 1,
            'general_affairs_work_vacation_management' => 1,
            'general_affairs_closing' => 1,
            'general_affairs_general_search' => 1,
            'general_affairs_vacation_management' => 1,
            'general_affairs_data_input_output' => 1,
            'general_affairs_master_management' => 1,
            'detail_no' => 13,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 14],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 0,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 1,
            'office_menu' => 1,
            'office_attendance_input' => 1,
            'office_work_vacation_management' => 1,
            'office_closing' => 1,
            'office_vacation_management' => 1,
            'office_general_search' => 1,
            'office_master_management' => 1,
            'general_affairs_menu' => 1,
            'general_affairs_attendance_input' => 1,
            'general_affairs_work_vacation_management' => 1,
            'general_affairs_closing' => 1,
            'general_affairs_general_search' => 1,
            'general_affairs_vacation_management' => 1,
            'general_affairs_data_input_output' => 1,
            'general_affairs_master_management' => 1,
            'detail_no' => 14,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 15],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 1,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 1,
            'office_menu' => 1,
            'office_attendance_input' => 1,
            'office_work_vacation_management' => 1,
            'office_closing' => 1,
            'office_vacation_management' => 1,
            'office_general_search' => 1,
            'office_master_management' => 1,
            'general_affairs_menu' => 1,
            'general_affairs_attendance_input' => 1,
            'general_affairs_work_vacation_management' => 1,
            'general_affairs_closing' => 1,
            'general_affairs_general_search' => 1,
            'general_affairs_vacation_management' => 1,
            'general_affairs_data_input_output' => 1,
            'general_affairs_master_management' => 1,
            'detail_no' => 15,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m011_authority_pattern')->updateOrInsert(
            ['authority_pattern_id' => 16],
            ['proxy_input_menu' => 1,
            'proxy_attendance_input' => 1,
            'proxy_input_target_setting' => 1,
            'attendance_admin_menu' => 1,
            'attendance_admin_inquiry_approval' => 1,
            'attendance_admin_work_vacation_management' => 1,
            'attendance_admin_daily_report' => 1,
            'attendance_admin_approval_target_setting' => 1,
            'office_menu' => 1,
            'office_attendance_input' => 1,
            'office_work_vacation_management' => 1,
            'office_closing' => 1,
            'office_vacation_management' => 1,
            'office_general_search' => 1,
            'office_master_management' => 1,
            'general_affairs_menu' => 1,
            'general_affairs_attendance_input' => 1,
            'general_affairs_work_vacation_management' => 1,
            'general_affairs_closing' => 1,
            'general_affairs_general_search' => 1,
            'general_affairs_vacation_management' => 1,
            'general_affairs_data_input_output' => 1,
            'general_affairs_master_management' => 1,
            'detail_no' => 16,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
    }
}
