<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class m031_unemployed_seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 1],
            ['unemployed_code' => '1',
            'unemployed_name' => '有休',
            'unemployed_short_name' => '有休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 1,
            'max_days' => 1,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 1,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 2],
            ['unemployed_code' => '2',
            'unemployed_name' => '半休',
            'unemployed_short_name' => '半休',
            'unemployed_take_unit_class' => 2,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 1,
            'max_days' => 1,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 2,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 3],
            ['unemployed_code' => '3',
            'unemployed_name' => '有休遅刻',
            'unemployed_short_name' => '有休遅',
            'unemployed_take_unit_class' => 4,
            'late_early_leave_class' => 1,
            'holiday_management_class' => 1,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 3,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 4],
            ['unemployed_code' => '4',
            'unemployed_name' => '遅刻(交通障害)',
            'unemployed_short_name' => '交通遅',
            'unemployed_take_unit_class' => 3,
            'late_early_leave_class' => 1,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 4,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 5],
            ['unemployed_code' => '5',
            'unemployed_name' => '有休早退',
            'unemployed_short_name' => '有休早',
            'unemployed_take_unit_class' => 4,
            'late_early_leave_class' => 2,
            'holiday_management_class' => 1,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 5,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 6],
            ['unemployed_code' => '6',
            'unemployed_name' => '欠勤',
            'unemployed_short_name' => '欠勤',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 6,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 7],
            ['unemployed_code' => '7',
            'unemployed_name' => '欠勤(半日)',
            'unemployed_short_name' => '半欠勤',
            'unemployed_take_unit_class' => 2,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 7,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 8],
            ['unemployed_code' => '8',
            'unemployed_name' => '欠勤遅刻',
            'unemployed_short_name' => '欠勤遅',
            'unemployed_take_unit_class' => 3,
            'late_early_leave_class' => 1,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 8,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 9],
            ['unemployed_code' => '9',
            'unemployed_name' => '欠勤早退',
            'unemployed_short_name' => '欠勤早',
            'unemployed_take_unit_class' => 3,
            'late_early_leave_class' => 2,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 9,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 10],
            ['unemployed_code' => '10',
            'unemployed_name' => '保存休暇',
            'unemployed_short_name' => '保存',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 2,
            'max_days' => 1,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 10,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 11],
            ['unemployed_code' => '11',
            'unemployed_name' => '保存休暇(半日)',
            'unemployed_short_name' => '保存半',
            'unemployed_take_unit_class' => 2,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 2,
            'max_days' => 1,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 11,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 12],
            ['unemployed_code' => '12',
            'unemployed_name' => '私用外出',
            'unemployed_short_name' => '外出',
            'unemployed_take_unit_class' => 3,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 12,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 13],
            ['unemployed_code' => '13',
            'unemployed_name' => '人間ドック休暇',
            'unemployed_short_name' => 'ドック',
            'unemployed_take_unit_class' => 2,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 13,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 14],
            ['unemployed_code' => '14',
            'unemployed_name' => '永年勤続休暇',
            'unemployed_short_name' => '永年',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 14,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 15],
            ['unemployed_code' => '15',
            'unemployed_name' => '結婚休暇',
            'unemployed_short_name' => '結婚',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 15,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 16],
            ['unemployed_code' => '16',
            'unemployed_name' => '服喪休暇',
            'unemployed_short_name' => '服喪',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 16,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 17],
            ['unemployed_code' => '17',
            'unemployed_name' => '業務外傷病回復後休暇',
            'unemployed_short_name' => '傷病',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 17,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 18],
            ['unemployed_code' => '18',
            'unemployed_name' => '業務外傷病回復後休暇（半日）',
            'unemployed_short_name' => '傷病半日',
            'unemployed_take_unit_class' => 2,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 18,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 19],
            ['unemployed_code' => '19',
            'unemployed_name' => '業務外傷病回復後等短縮勤務',
            'unemployed_short_name' => '傷病短',
            'unemployed_take_unit_class' => 3,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 1,
            'deduction_target_class' => 2,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 19,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 20],
            ['unemployed_code' => '20',
            'unemployed_name' => '生理休暇',
            'unemployed_short_name' => '生休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 20,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 21],
            ['unemployed_code' => '21',
            'unemployed_name' => '天災/交通事情休暇(有給)',
            'unemployed_short_name' => '天災有休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 21,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 22],
            ['unemployed_code' => '22',
            'unemployed_name' => '天災/交通事情休暇(無給)',
            'unemployed_short_name' => '天災無給',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 22,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 23],
            ['unemployed_code' => '23',
            'unemployed_name' => '伝染病予防法隔離休暇',
            'unemployed_short_name' => '伝休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 23,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 24],
            ['unemployed_code' => '24',
            'unemployed_name' => '就業禁止休暇',
            'unemployed_short_name' => '就業禁',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 24,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 25],
            ['unemployed_code' => '25',
            'unemployed_name' => '特別休暇(その他有給)',
            'unemployed_short_name' => '特有休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 25,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 26],
            ['unemployed_code' => '26',
            'unemployed_name' => '特別休暇(その他無給)',
            'unemployed_short_name' => '特無休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 26,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 27],
            ['unemployed_code' => '27',
            'unemployed_name' => '時間内活動(支給あり)',
            'unemployed_short_name' => '時間内活有',
            'unemployed_take_unit_class' => 3,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 27,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 28],
            ['unemployed_code' => '28',
            'unemployed_name' => '時間内活動(支給なし)',
            'unemployed_short_name' => '時間内無',
            'unemployed_take_unit_class' => 3,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 28,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 29],
            ['unemployed_code' => '29',
            'unemployed_name' => '産前産後休業',
            'unemployed_short_name' => '産休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 29,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 30],
            ['unemployed_code' => '30',
            'unemployed_name' => '育児休業',
            'unemployed_short_name' => '育休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 30,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 31],
            ['unemployed_code' => '31',
            'unemployed_name' => '育児短縮',
            'unemployed_short_name' => '育短',
            'unemployed_take_unit_class' => 3,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 1,
            'deduction_target_class' => 2,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 31,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 32],
            ['unemployed_code' => '32',
            'unemployed_name' => '看護休暇',
            'unemployed_short_name' => '看休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 32,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 33],
            ['unemployed_code' => '33',
            'unemployed_name' => '母性健康管理休暇',
            'unemployed_short_name' => '母休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 1,
            'deduction_target_class' => 2,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 33,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 34],
            ['unemployed_code' => '34',
            'unemployed_name' => '育児時間',
            'unemployed_short_name' => '育時',
            'unemployed_take_unit_class' => 3,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 1,
            'deduction_target_class' => 2,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 34,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 35],
            ['unemployed_code' => '35',
            'unemployed_name' => '介護休業',
            'unemployed_short_name' => '介護業',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 35,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 36],
            ['unemployed_code' => '36',
            'unemployed_name' => '介護休暇',
            'unemployed_short_name' => '介護暇',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 36,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 37],
            ['unemployed_code' => '37',
            'unemployed_name' => '私傷病休職',
            'unemployed_short_name' => '私休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 37,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 38],
            ['unemployed_code' => '38',
            'unemployed_name' => '事故欠勤休職',
            'unemployed_short_name' => '事故休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 38,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 39],
            ['unemployed_code' => '39',
            'unemployed_name' => '起訴休職',
            'unemployed_short_name' => '起訴休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 39,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 40],
            ['unemployed_code' => '40',
            'unemployed_name' => '公職休職',
            'unemployed_short_name' => '公職休',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 40,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 41],
            ['unemployed_code' => '41',
            'unemployed_name' => '休職(その他有給)',
            'unemployed_short_name' => '他有給',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 1,
            'work_day_target_class' => 1,
            'deduction_target_class' => 0,
            'bonus_absenteeism_deduction_class' => 0,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 41,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m031_unemployed')->updateOrInsert(
            ['unemployed_id' => 42],
            ['unemployed_code' => '42',
            'unemployed_name' => '休職(その他無給)',
            'unemployed_short_name' => '他無給',
            'unemployed_take_unit_class' => 1,
            'late_early_leave_class' => 0,
            'holiday_management_class' => 0,
            'max_days' => 0,
            'paid_leave_target_class' => 0,
            'work_day_target_class' => 0,
            'deduction_target_class' => 1,
            'bonus_absenteeism_deduction_class' => 1,
            'manual_grant_enabled_class' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 42,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
    }
}
