<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class m033_grant_paid_leave_pattern_seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 1],
            ['prescribed_week_days' => 5,
            'service_length_from' => 0,
            'service_length_to' => 5,
            'grant_paid_leave_days' => 0,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 1,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 2],
            ['prescribed_week_days' => 5,
            'service_length_from' => 6,
            'service_length_to' => 17,
            'grant_paid_leave_days' => 10,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 2,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 3],
            ['prescribed_week_days' => 5,
            'service_length_from' => 18,
            'service_length_to' => 29,
            'grant_paid_leave_days' => 11,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 3,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 4],
            ['prescribed_week_days' => 5,
            'service_length_from' => 30,
            'service_length_to' => 41,
            'grant_paid_leave_days' => 12,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 4,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 5],
            ['prescribed_week_days' => 5,
            'service_length_from' => 42,
            'service_length_to' => 53,
            'grant_paid_leave_days' => 14,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 5,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 6],
            ['prescribed_week_days' => 5,
            'service_length_from' => 54,
            'service_length_to' => 65,
            'grant_paid_leave_days' => 16,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 6,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 7],
            ['prescribed_week_days' => 5,
            'service_length_from' => 66,
            'service_length_to' => 77,
            'grant_paid_leave_days' => 18,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 7,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 8],
            ['prescribed_week_days' => 5,
            'service_length_from' => 78,
            'service_length_to' => 999,
            'grant_paid_leave_days' => 20,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 8,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 9],
            ['prescribed_week_days' => 4,
            'service_length_from' => 0,
            'service_length_to' => 5,
            'grant_paid_leave_days' => 0,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 9,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 10],
            ['prescribed_week_days' => 4,
            'service_length_from' => 6,
            'service_length_to' => 17,
            'grant_paid_leave_days' => 7,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 10,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 11],
            ['prescribed_week_days' => 4,
            'service_length_from' => 18,
            'service_length_to' => 29,
            'grant_paid_leave_days' => 8,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 11,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 12],
            ['prescribed_week_days' => 4,
            'service_length_from' => 30,
            'service_length_to' => 41,
            'grant_paid_leave_days' => 9,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 12,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 13],
            ['prescribed_week_days' => 4,
            'service_length_from' => 42,
            'service_length_to' => 53,
            'grant_paid_leave_days' => 10,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 13,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 14],
            ['prescribed_week_days' => 4,
            'service_length_from' => 54,
            'service_length_to' => 65,
            'grant_paid_leave_days' => 12,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 14,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 15],
            ['prescribed_week_days' => 4,
            'service_length_from' => 66,
            'service_length_to' => 77,
            'grant_paid_leave_days' => 13,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 15,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 16],
            ['prescribed_week_days' => 4,
            'service_length_from' => 78,
            'service_length_to' => 999,
            'grant_paid_leave_days' => 15,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 16,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 17],
            ['prescribed_week_days' => 3,
            'service_length_from' => 0,
            'service_length_to' => 5,
            'grant_paid_leave_days' => 0,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 17,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 18],
            ['prescribed_week_days' => 3,
            'service_length_from' => 6,
            'service_length_to' => 17,
            'grant_paid_leave_days' => 5,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 18,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 19],
            ['prescribed_week_days' => 3,
            'service_length_from' => 18,
            'service_length_to' => 29,
            'grant_paid_leave_days' => 6,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 19,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 20],
            ['prescribed_week_days' => 3,
            'service_length_from' => 30,
            'service_length_to' => 41,
            'grant_paid_leave_days' => 6,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 20,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 21],
            ['prescribed_week_days' => 3,
            'service_length_from' => 42,
            'service_length_to' => 53,
            'grant_paid_leave_days' => 8,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 21,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 22],
            ['prescribed_week_days' => 3,
            'service_length_from' => 54,
            'service_length_to' => 65,
            'grant_paid_leave_days' => 9,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 22,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 23],
            ['prescribed_week_days' => 3,
            'service_length_from' => 66,
            'service_length_to' => 77,
            'grant_paid_leave_days' => 10,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 23,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 24],
            ['prescribed_week_days' => 3,
            'service_length_from' => 78,
            'service_length_to' => 999,
            'grant_paid_leave_days' => 11,
            'obligatory_take_paid_leave_days' => 5,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 24,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 25],
            ['prescribed_week_days' => 2,
            'service_length_from' => 0,
            'service_length_to' => 5,
            'grant_paid_leave_days' => 0,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 25,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 26],
            ['prescribed_week_days' => 2,
            'service_length_from' => 6,
            'service_length_to' => 17,
            'grant_paid_leave_days' => 3,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 26,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 27],
            ['prescribed_week_days' => 2,
            'service_length_from' => 18,
            'service_length_to' => 29,
            'grant_paid_leave_days' => 4,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 27,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 28],
            ['prescribed_week_days' => 2,
            'service_length_from' => 30,
            'service_length_to' => 41,
            'grant_paid_leave_days' => 4,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 28,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 29],
            ['prescribed_week_days' => 2,
            'service_length_from' => 42,
            'service_length_to' => 53,
            'grant_paid_leave_days' => 5,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 29,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 30],
            ['prescribed_week_days' => 2,
            'service_length_from' => 54,
            'service_length_to' => 65,
            'grant_paid_leave_days' => 6,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 30,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 31],
            ['prescribed_week_days' => 2,
            'service_length_from' => 66,
            'service_length_to' => 77,
            'grant_paid_leave_days' => 6,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 31,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 32],
            ['prescribed_week_days' => 2,
            'service_length_from' => 78,
            'service_length_to' => 999,
            'grant_paid_leave_days' => 7,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 32,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 33],
            ['prescribed_week_days' => 1,
            'service_length_from' => 0,
            'service_length_to' => 5,
            'grant_paid_leave_days' => 0,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 33,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 34],
            ['prescribed_week_days' => 1,
            'service_length_from' => 6,
            'service_length_to' => 17,
            'grant_paid_leave_days' => 1,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 34,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 35],
            ['prescribed_week_days' => 1,
            'service_length_from' => 18,
            'service_length_to' => 29,
            'grant_paid_leave_days' => 2,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 35,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 36],
            ['prescribed_week_days' => 1,
            'service_length_from' => 30,
            'service_length_to' => 41,
            'grant_paid_leave_days' => 2,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 36,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 37],
            ['prescribed_week_days' => 1,
            'service_length_from' => 42,
            'service_length_to' => 53,
            'grant_paid_leave_days' => 2,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 37,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 38],
            ['prescribed_week_days' => 1,
            'service_length_from' => 54,
            'service_length_to' => 65,
            'grant_paid_leave_days' => 3,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 38,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 39],
            ['prescribed_week_days' => 1,
            'service_length_from' => 66,
            'service_length_to' => 77,
            'grant_paid_leave_days' => 3,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 39,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m033_grant_paid_leave_pattern')->updateOrInsert(
            ['grant_paid_leave_pattern_id' => 40],
            ['prescribed_week_days' => 1,
            'service_length_from' => 78,
            'service_length_to' => 999,
            'grant_paid_leave_days' => 3,
            'obligatory_take_paid_leave_days' => 0,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 40,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
    }
}
