<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class m039_prevention_overwork_check_seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 1],
            ['violation_warning_type_id' => 1,
            'violation_warning_id' => 2,
            'time_or_count' => 8,
            'message' => '時間外時間が8時間を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 1,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 2],
            ['violation_warning_type_id' => 1,
            'violation_warning_id' => 1,
            'time_or_count' => 20,
            'message' => '時間外時間が20時間を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 2,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 3],
            ['violation_warning_type_id' => 2,
            'violation_warning_id' => 2,
            'time_or_count' => 45,
            'message' => '時間外時間が45時間を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 3,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 4],
            ['violation_warning_type_id' => 3,
            'violation_warning_id' => 1,
            'time_or_count' => 180,
            'message' => '年間時間外時間が180時間を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 4,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 5],
            ['violation_warning_type_id' => 3,
            'violation_warning_id' => 2,
            'time_or_count' => 360,
            'message' => '年間時間外時間が360時間を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 5,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 6],
            ['violation_warning_type_id' => 4,
            'violation_warning_id' => 1,
            'time_or_count' => 80,
            'message' => '時間外時間が80時間を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 6,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 7],
            ['violation_warning_type_id' => 4,
            'violation_warning_id' => 2,
            'time_or_count' => 100,
            'message' => '時間外時間が100時間を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 7,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 8],
            ['violation_warning_type_id' => 5,
            'violation_warning_id' => 1,
            'time_or_count' => 540,
            'message' => '年間時間外時間が540時間を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 8,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 9],
            ['violation_warning_type_id' => 5,
            'violation_warning_id' => 2,
            'time_or_count' => 720,
            'message' => '年間時間外時間が720時間を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 9,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 10],
            ['violation_warning_type_id' => 6,
            'violation_warning_id' => 1,
            'time_or_count' => 60,
            'message' => '2～6か月平均の時間外時間が60時間を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 10,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 11],
            ['violation_warning_type_id' => 6,
            'violation_warning_id' => 2,
            'time_or_count' => 80,
            'message' => '2～6か月平均の時間外時間が80時間を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 11,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 12],
            ['violation_warning_type_id' => 7,
            'violation_warning_id' => 1,
            'time_or_count' => 3,
            'message' => '年間特別条項適用回数が4回を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 12,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 13],
            ['violation_warning_type_id' => 7,
            'violation_warning_id' => 2,
            'time_or_count' => 5,
            'message' => '年間特別条項適用回数が6回を超えています',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 13,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 14],
            ['violation_warning_type_id' => 1,
            'violation_warning_id' => 1,
            'time_or_count' => 0,
            'message' => '削除ダミー',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 14,
            'is_delete' => 1,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 15],
            ['violation_warning_type_id' => 1,
            'violation_warning_id' => 1,
            'time_or_count' => 0,
            'message' => '無効ダミー',
            'valid_date_start' => 0,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 15,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 16],
            ['violation_warning_type_id' => 1,
            'violation_warning_id' => 1,
            'time_or_count' => 0,
            'message' => '期間外ダミー１',
            'valid_date_start' => 0,
            'valid_date_end' => 44287,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 16,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
        DB::table('m039_prevention_overwork_check')->updateOrInsert(
            ['prevention_overwork_check_id' => 17],
            ['violation_warning_type_id' => 1,
            'violation_warning_id' => 1,
            'time_or_count' => 0,
            'message' => '期間外ダミー２',
            'valid_date_start' => 44562,
            'valid_date_end' => 2958465,
            'valid_class' => 1,
            'company_id' => 0,
            'is_invalid' => 0,
            'origin_id' => 0,
            'detail_no' => 17,
            'is_delete' => 0,
            'created_user' => 'SYSTEM',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_user' => 'SYSTEM',
            'updated_at' => date('Y-m-d H:i:s'),
            ]
        );
    }
}
